apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zfs-sync-operator
rules:
- apiGroups:
  - zfs-sync-operator.johnstarich.com
  resources:
  - backups
  - backups/status
  - pools
  - pools/status
  - poolsnapshots
  - poolsnapshots/status
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
