apiVersion: apps/v1
kind: Deployment
metadata:
  name: zfs-sync-operator
  labels:
    app: zfs-sync-operator
spec:
  selector:
    matchLabels:
      app: zfs-sync-operator
  template:
    metadata:
      labels:
        app: zfs-sync-operator
    spec:
      containers:
        - name: zfs-sync-operator
          image: "ghcr.io/johnstarich/zfs-sync-operator:{{ .Chart.Version }}"
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: zfs-sync-operator
