apiVersion: apps/v1
kind: Deployment
metadata:
  name: zfs-sync-operator
  namespace: zfs-sync-operator-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zfs-sync-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: zfs-sync-operator
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - zfs-sync-operator
            topologyKey: kubernetes.io/hostname
      containers:
      - image: ghcr.io/johnstarich/zfs-sync-operator:latest
        imagePullPolicy: Always
        name: operator
      imagePullSecrets:
      - name: github-pull-secret
