apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: backups.zfs-sync-operator.johnstarich.com
spec:
  group: zfs-sync-operator.johnstarich.com
  scope: Namespaced
  names:
    plural: backups
    singular: backup
    kind: Backup
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              source:
                type: object
                properties:
                  name:
                    type: string
              destination:
                type: object
                properties:
                  name:
                    type: string
          status:
            type: object
            properties:
              state:
                type: string
              reason:
                type: string
              lastSentSnapshot:
                type: object
                properties:
                  name:
                    type: string
    subresources:
      status: {}
    selectableFields: []
    additionalPrinterColumns:
    - jsonPath: .status.state
      name: Status
      type: string
