apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pools.zfs-sync-operator.johnstarich.com
spec:
  group: zfs-sync-operator.johnstarich.com
  scope: Namespaced
  names:
    plural: pools
    singular: pool
    kind: Pool
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
              ssh:
                type: object
                properties:
                  user:
                    type: string
                  address:
                    type: string
                  hostKey:
                    type: string
                    format: byte
                  privateKey:
                    type: object
                    properties:
                      name:
                        type: string
                      key:
                        type: string
              wireguard:
                type: object
                properties:
                  dnsAddresses:
                    type: array
                    items:
                      type: string
                  localAddress:
                    type: string
                  localPrivateKey:
                    type: object
                    properties:
                      name:
                        type: string
                      key:
                        type: string
                  peerAddress:
                    type: string
                  peerPublicKey:
                    type: object
                    properties:
                      name:
                        type: string
                      key:
                        type: string
                  presharedKey:
                    type: object
                    properties:
                      name:
                        type: string
                      key:
                        type: string
              snapshots:
                type: object
                properties:
                  template:
                    type: object
                    properties:
                      datasets:
                        type: array
                        minItems: 1
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            recursive:
                              type: object
                              properties:
                                skipChildren:
                                  type: array
                                  items:
                                    type: string
                  intervals:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        historyLimit:
                          type: integer
                        interval:
                          type: string
          status:
            type: object
            properties:
              state:
                type: string
              reason:
                type: string
    subresources:
      status: {}
    selectableFields: []
    additionalPrinterColumns:
    - jsonPath: .spec.name
      name: Pool Name
      type: string
    - jsonPath: .status.state
      name: Status
      type: string
    - jsonPath: .status.reason
      name: Details
      type: string
